music_directory    "~/onedrive/Music"
playlist_directory "~/.config/mpd/playlists"
db_file            "~/.config/mpd/database"
state_file         "~/.config/mpd/state"

audio_output {
  type "pipewire"
  name "pipewire"
}
